import { Controller, Get, Header, StreamableFile } from '@nestjs/common';

@Controller('content/afisha')
export class StaticController {
  // 1x1 JPEG (black pixel). Enough for content-type checks.
  private static readonly jpegBase64 =
    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAALCAAaABoBAREA/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAACAgIDAQAAAAAAAAAAAAABAgADBAURBhIh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAREC/9oADAMBAAIRAxEAPwCkY8mKqZ1d0b7bY1x9tOQzqH3n5oLqX7Wq0q5VZpDq2Gg9zq1tUq6vSg1y8yJr8l3lQeQ1VtN7p7Yq8xq8sYJwD6f/2Q==';

  @Get()
  @Header('Content-Type', 'image/jpeg')
  getAfishaRoot(): StreamableFile {
    const buffer = Buffer.from(StaticController.jpegBase64, 'base64');
    return new StreamableFile(buffer);
  }
}

